//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcesamientoColasDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLAS()
        {
            this.PROCESAMIENTO_COLA = new HashSet<PROCESAMIENTO_COLA>();
        }
    
        public int COLA_ID { get; set; }
        public string COLA_NAME { get; set; }
        public string COLA_DESCRIPTION { get; set; }
        public int COLA_TIEMPO { get; set; }
        public string COLA_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESAMIENTO_COLA> PROCESAMIENTO_COLA { get; set; }
    }
}
